{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1c535e8f-c1f5-468c-9161-9687544a1907",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-03-26 05:56:13.469 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.470 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.755 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-03-26 05:56:13.756 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.757 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.759 No runtime found, using MemoryCacheStorageManager\n",
      "2026-03-26 05:56:13.762 No runtime found, using MemoryCacheStorageManager\n",
      "2026-03-26 05:56:13.764 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.765 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.766 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.767 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.880 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.881 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.882 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.883 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.884 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.885 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.886 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.888 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.889 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.890 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.892 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.893 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.894 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.896 Session state does not function when running a script without `streamlit run`\n",
      "2026-03-26 05:56:13.897 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.898 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.901 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.904 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.907 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.907 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.912 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.951 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2026-03-26 05:56:13.954 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.959 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.960 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.961 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.965 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:13.996 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2026-03-26 05:56:14.003 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.004 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.006 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.007 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.009 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.018 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2026-03-26 05:56:14.021 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.022 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.023 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.023 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.024 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.026 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.027 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.028 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.028 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.029 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.031 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.032 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.033 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.034 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.035 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.036 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.037 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.039 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.040 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.040 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.402 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2026-03-26 05:56:14.409 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.417 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.417 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.419 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.425 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.426 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.427 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.435 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.438 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.444 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.489 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2026-03-26 05:56:14.497 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.498 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.499 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.499 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-26 05:56:14.503 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import plotly.graph_objects as go\n",
    "import plotly.express as px\n",
    "from plotly.subplots import make_subplots\n",
    "\n",
    "# --- 1. הגדרות דף ---\n",
    "st.set_page_config(page_title=\"Amazon Logistics & Sales Dashboard\", layout=\"wide\")\n",
    "\n",
    "# צמצום רווחים בראש הדף\n",
    "st.markdown(\"\"\"\n",
    "    <style>\n",
    "           .block-container {\n",
    "                padding-top: 1rem;\n",
    "                padding-bottom: 0rem;\n",
    "            }\n",
    "    </style>\n",
    "    \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "@st.cache_data\n",
    "def load_and_clean_data():\n",
    "    # טעינת הקובץ (שכבר מכיל את נתוני המלאי לאחר ה-Join)\n",
    "    df = pd.read_csv('amazon_cleaned.csv')\n",
    "    \n",
    "    # המרת תאריך\n",
    "    df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True, errors='coerce')\n",
    "    \n",
    "    # חילוץ מותג (מילה ראשונה משם המוצר)\n",
    "    df['brand'] = df['product_name'].str.split().str[0]\n",
    "    \n",
    "    return df\n",
    "\n",
    "try:\n",
    "    df = load_and_clean_data()\n",
    "    \n",
    "    st.title(\"📊 Amazon Business & Inventory Insights\")\n",
    "\n",
    "    # --- 2. סרגל צד (Sidebar) ---\n",
    "    st.sidebar.header(\"מסננים\")\n",
    "    categories = sorted(df['main_category'].dropna().unique())\n",
    "    selected_cat = st.sidebar.selectbox(\"בחר קטגוריה מובילה:\", categories)\n",
    "\n",
    "    # סינון הנתונים לפי הבחירה\n",
    "    filtered_df = df[df['main_category'] == selected_cat].copy()\n",
    "\n",
    "    if not filtered_df.empty:\n",
    "        \n",
    "        # --- 3. חלק עליון: מחוונים (Gauges) ---\n",
    "        upper_charts_height = 350\n",
    "        col1, col2, col3 = st.columns(3)\n",
    "\n",
    "        with col1:\n",
    "            # מד אוץ 1: אימות איכות (Rating)\n",
    "            avg_rating = filtered_df['rating'].mean()\n",
    "            fig_rating = go.Figure(go.Indicator(\n",
    "                mode = \"gauge+number\",\n",
    "                value = avg_rating,\n",
    "                title = {'text': \"דירוג ממוצע\", 'font': {'size': 18}},\n",
    "                gauge = {\n",
    "                    'axis': {'range': [0, 5]},\n",
    "                    'bar': {'color': \"black\"},\n",
    "                    'steps': [\n",
    "                        {'range': [0, 3.8], 'color': \"#FF4B4B\"},\n",
    "                        {'range': [3.8, 4.2], 'color': \"#FFA500\"},\n",
    "                        {'range': [4.2, 5], 'color': \"#238636\"}\n",
    "                    ]\n",
    "                }\n",
    "            ))\n",
    "            fig_rating.update_layout(height=upper_charts_height, margin=dict(t=50, b=0))\n",
    "            st.plotly_chart(fig_rating, use_container_width=True)\n",
    "\n",
    "        with col2:\n",
    "            # מד אוץ 2: בריאות המלאי (כמה מוצרים מעל הסף)\n",
    "            # חישוב אחוז המוצרים שתקינים מבחינת מלאי\n",
    "            in_stock_count = len(filtered_df[filtered_df['stock_level'] > filtered_df['restock_threshold']])\n",
    "            health_score = (in_stock_count / len(filtered_df)) * 100\n",
    "\n",
    "            fig_inventory = go.Figure(go.Indicator(\n",
    "                mode = \"gauge+number\",\n",
    "                value = health_score,\n",
    "                number = {'suffix': \"%\"},\n",
    "                title = {'text': \"בריאות המלאי (מעל הסף)\", 'font': {'size': 18}},\n",
    "                gauge = {\n",
    "                    'axis': {'range': [0, 100]},\n",
    "                    'bar': {'color': \"#0066CC\"},\n",
    "                    'steps': [\n",
    "                        {'range': [0, 40], 'color': \"#FFCC00\"},\n",
    "                        {'range': [40, 100], 'color': \"#99FF99\"}\n",
    "                    ],\n",
    "                    'threshold': {'line': {'color': \"red\", 'width': 4}, 'value': 30}\n",
    "                }\n",
    "            ))\n",
    "            fig_inventory.update_layout(height=upper_charts_height, margin=dict(t=50, b=0))\n",
    "            st.plotly_chart(fig_inventory, use_container_width=True)\n",
    "\n",
    "        with col3:\n",
    "            # מד אוץ 3: עומק הנחות ממוצע\n",
    "            avg_discount = filtered_df['discount_percentage'].mean() * 100\n",
    "            fig_discount = go.Figure(go.Indicator(\n",
    "                mode = \"gauge+number\",\n",
    "                value = avg_discount,\n",
    "                number = {'suffix': \"%\"},\n",
    "                title = {'text': \"הנחה ממוצעת\", 'font': {'size': 18}},\n",
    "                gauge = {\n",
    "                    'axis': {'range': [0, 100]},\n",
    "                    'bar': {'color': \"purple\"},\n",
    "                    'steps': [{'range': [0, 100], 'color': \"lightgray\"}]\n",
    "                }\n",
    "            ))\n",
    "            fig_discount.update_layout(height=upper_charts_height, margin=dict(t=50, b=0))\n",
    "            st.plotly_chart(fig_discount, use_container_width=True)\n",
    "\n",
    "        # --- 4. חלק אמצעי: טבלת מדדים ונתח שוק ---\n",
    "        st.markdown(\"---\")\n",
    "        m_col1, m_col2 = st.columns([1, 2])\n",
    "\n",
    "        with m_col1:\n",
    "            st.subheader(\"סיכום מהיר\")\n",
    "            st.metric(\"סה\\\"כ מוצרים\", f\"{len(filtered_df):,}\")\n",
    "            st.metric(\"סה\\\"כ ביקורות\", f\"{filtered_df['rating_count'].sum():,.0f}\")\n",
    "            \n",
    "            # התראה על מוצרים בסיכון\n",
    "            low_stock_items = len(filtered_df[filtered_df['stock_level'] <= filtered_df['restock_threshold']])\n",
    "            if low_stock_items > 0:\n",
    "                st.warning(f\"שים לב: ישנם {low_stock_items} מוצרים מתחת לסף המלאי!\")\n",
    "\n",
    "        with m_col2:\n",
    "            # נתח שוק לפי מותגים (Donut Chart)\n",
    "            brand_counts = filtered_df.groupby('brand')['rating_count'].sum().nlargest(8).reset_index()\n",
    "            fig_pie = px.pie(brand_counts, values='rating_count', names='brand', \n",
    "                             title=\"דומיננטיות מותגים (לפי כמות ביקורות)\", hole=0.4)\n",
    "            fig_pie.update_layout(height=400)\n",
    "            st.plotly_chart(fig_pie, use_container_width=True)\n",
    "\n",
    "        # --- 5. חלק תחתון: מגמות זמן ---\n",
    "        st.markdown(\"---\")\n",
    "        st.subheader(\"מגמות מכירות ודירוג לאורך זמן\")\n",
    "        \n",
    "        filtered_df['month_year'] = filtered_df['order_date'].dt.to_period('M').astype(str)\n",
    "        monthly = filtered_df.groupby('month_year').agg({'rating_count': 'sum', 'rating': 'mean'}).reset_index()\n",
    "\n",
    "        fig_trend = make_subplots(specs=[[{\"secondary_y\": True}]])\n",
    "        fig_trend.add_trace(go.Bar(x=monthly['month_year'], y=monthly['rating_count'], name=\"מכירות (Reviews)\"), secondary_y=False)\n",
    "        fig_trend.add_trace(go.Scatter(x=monthly['month_year'], y=monthly['rating'], name=\"דירוג ⭐\", line=dict(color='orange')), secondary_y=True)\n",
    "        \n",
    "        fig_trend.update_layout(height=450, legend=dict(orientation=\"h\", y=1.1))\n",
    "        st.plotly_chart(fig_trend, use_container_width=True)\n",
    "\n",
    "    else:\n",
    "        st.info(\"בחר קטגוריה מהתפריט בצד כדי להציג את הנתונים.\")\n",
    "\n",
    "except Exception as e:\n",
    "    st.error(f\"שגיאה בטעינת הנתונים: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0129946f-5590-4d2a-af92-da0489fd546d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "anaconda-2025.12-py312",
   "language": "python",
   "name": "conda-env-anaconda-2025.12-py312-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
