{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1c535e8f-c1f5-468c-9161-9687544a1907",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-03-29 19:26:28.635 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.636 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.817 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-03-29 19:26:28.818 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.818 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.819 No runtime found, using MemoryCacheStorageManager\n",
      "2026-03-29 19:26:28.821 No runtime found, using MemoryCacheStorageManager\n",
      "2026-03-29 19:26:28.822 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.822 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.823 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.823 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.881 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.882 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.882 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.883 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.883 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.884 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.885 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.886 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.886 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.887 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.887 Session state does not function when running a script without `streamlit run`\n",
      "2026-03-29 19:26:28.888 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.888 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.890 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.892 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.892 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.893 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.893 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.919 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2026-03-29 19:26:28.922 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.922 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.923 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.923 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.924 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.930 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2026-03-29 19:26:28.931 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.932 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.933 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.934 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:28.934 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.044 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2026-03-29 19:26:29.046 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.047 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.047 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.048 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.048 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.049 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.049 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.050 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.050 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.051 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.051 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.052 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.087 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.087 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.088 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.088 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.089 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.090 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.090 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.091 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.093 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.096 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.098 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.099 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.099 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.100 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.100 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.101 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.101 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.102 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.103 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.104 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.105 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.105 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.129 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2026-03-29 19:26:29.130 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.131 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.131 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.132 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-29 19:26:29.132 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import plotly.graph_objects as go\n",
    "import plotly.express as px\n",
    "from plotly.subplots import make_subplots\n",
    "\n",
    "# 1. הגדרות דף רחב\n",
    "st.set_page_config(page_title=\"Amazon Dashboard\", layout=\"wide\")\n",
    "\n",
    "# עיצוב CSS ליישור לימין, התאמת טבלאות וצמצום רווחים\n",
    "st.markdown(\"\"\"\n",
    "    <style>\n",
    "    .block-container {\n",
    "        padding-top: 1rem;\n",
    "        padding-bottom: 0rem;\n",
    "    }\n",
    "    /* יישור לימין של טקסט וטבלאות */\n",
    "    .main {\n",
    "        direction: rtl;\n",
    "        text-align: right;\n",
    "    }\n",
    "    div[data-testid=\"stTable\"] {\n",
    "        direction: rtl;\n",
    "        text-align: right;\n",
    "    }\n",
    "    /* יישור כותרות של מטריקות לימין */\n",
    "    div[data-testid=\"stMetricValue\"] > div {\n",
    "        text-align: right;\n",
    "        direction: rtl;\n",
    "    }\n",
    "    </style>\n",
    "    \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "@st.cache_data\n",
    "def load_data():\n",
    "    df = pd.read_csv('amazon_cleaned.csv')\n",
    "    df.columns = df.columns.str.strip()\n",
    "    df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True, errors='coerce')\n",
    "    return df\n",
    "\n",
    "try:\n",
    "    df = load_data()\n",
    "    st.title(\"📊 Amazon Business Insights Dashboard\")\n",
    "\n",
    "    # סינון לפי קטגוריה\n",
    "    categories = sorted(df['main_category'].dropna().unique())\n",
    "    selected_cat = st.sidebar.selectbox(\"בחר קטגוריה\", categories)\n",
    "    filtered_df = df[df['main_category'] == selected_cat].copy()\n",
    "\n",
    "    if not filtered_df.empty:\n",
    "        # הגדרת גובה אחיד לכל הגרפים בשורה העליונה\n",
    "        charts_height = 400 \n",
    "        col1, col2, col3 = st.columns([1, 1, 1])\n",
    "\n",
    "        # --- עמודה 1: מדד איכות (Rating) ---\n",
    "        with col1:\n",
    "            avg_rating = filtered_df['rating'].mean()\n",
    "            fig_gauge_rating = go.Figure(go.Indicator(\n",
    "                mode = \"gauge+number\", value = avg_rating,\n",
    "                title = {'text': \"מדד איכות ממוצע\", 'font': {'size': 20}},\n",
    "                gauge = {\n",
    "                    'axis': {'range': [0, 5]}, \n",
    "                    'bar': {'color': \"black\"},\n",
    "                    'steps': [\n",
    "                        {'range': [0, 3.5], 'color': '#FF4B4B'},\n",
    "                        {'range': [3.5, 4.2], 'color': '#FFD700'},\n",
    "                        {'range': [4.2, 5], 'color': '#238636'}\n",
    "                    ]\n",
    "                }\n",
    "            ))\n",
    "            fig_gauge_rating.update_layout(height=charts_height, margin=dict(t=80, b=20, l=30, r=30))\n",
    "            st.plotly_chart(fig_gauge_rating, use_container_width=True)\n",
    "\n",
    "        # --- עמודה 2: בריאות המלאי (Inventory Health) ---\n",
    "        with col2:\n",
    "            total_items = len(filtered_df)\n",
    "            healthy_items = len(filtered_df[filtered_df['rating'] >= 4.0])\n",
    "            health_score = (healthy_items / total_items) * 100 if total_items > 0 else 0\n",
    "            \n",
    "            fig_gauge_inv = go.Figure(go.Indicator(\n",
    "                mode = \"gauge+number\", value = health_score, number = {'suffix': \"%\"},\n",
    "                title = {'text': \"בריאות המלאי (Rating > 4.0)\", 'font': {'size': 20}},\n",
    "                gauge = {\n",
    "                    'axis': {'range': [0, 100]}, \n",
    "                    'bar': {'color': \"black\"},\n",
    "                    'steps': [\n",
    "                        {'range': [0, 40], 'color': '#FF4B4B'},\n",
    "                        {'range': [40, 75], 'color': '#FFD700'},\n",
    "                        {'range': [75, 100], 'color': '#238636'}\n",
    "                    ]\n",
    "                }\n",
    "            ))\n",
    "            fig_gauge_inv.update_layout(height=charts_height, margin=dict(t=80, b=20, l=30, r=30))\n",
    "            st.plotly_chart(fig_gauge_inv, use_container_width=True)\n",
    "\n",
    "        # --- עמודה 3: דומיננטיות מותגים ---\n",
    "        with col3:\n",
    "            filtered_df['brand'] = filtered_df['product_name'].str.split().str[0]\n",
    "            brand_stats = filtered_df.groupby('brand')['rating_count'].sum().nlargest(7).reset_index()\n",
    "            fig_pie = px.pie(brand_stats, values='rating_count', names='brand', \n",
    "                             title=\"דומיננטיות מותגים (לפי Reviews)\", hole=0.4)\n",
    "            # התאמת גודל הפאי שיהיה פרופורציונלי למדדי האוץ\n",
    "            fig_pie.update_layout(height=charts_height, margin=dict(t=80, b=20, l=30, r=30),\n",
    "                                  legend=dict(orientation=\"h\", yanchor=\"bottom\", y=-0.2, xanchor=\"center\", x=0.5))\n",
    "            st.plotly_chart(fig_pie, use_container_width=True)\n",
    "\n",
    "        st.markdown(\"---\")\n",
    "\n",
    "        # --- שיפור 2: טבלת נתונים כלליים (הועלתה למעלה) ---\n",
    "        st.subheader(\"📋 נתונים כלליים לקטגוריה\")\n",
    "        general_data = pd.DataFrame({\n",
    "            \"מדד\": [\"כמות דירוגים\", \"כמות מוצרים\", \"דירוג ממוצע\"],\n",
    "            \"ערך\": [\n",
    "                f\"{filtered_df['rating_count'].sum():,.0f}\",\n",
    "                f\"{len(filtered_df):,}\",\n",
    "                f\"{avg_rating:.2f} ⭐\"\n",
    "            ]\n",
    "        })\n",
    "        st.table(general_data)\n",
    "\n",
    "        st.markdown(\"---\")\n",
    "\n",
    "        # --- שיפור 3: טבלת הסבר למדד בריאות המלאי ---\n",
    "        st.subheader(\"💡 כיצד חושב מדד בריאות המלאי?\")\n",
    "        poor = filtered_df[filtered_df['rating'] < 3.5]\n",
    "        fair = filtered_df[(filtered_df['rating'] >= 3.5) & (filtered_df['rating'] < 4.0)]\n",
    "        good = filtered_df[filtered_df['rating'] >= 4.0]\n",
    "\n",
    "        explanation_df = pd.DataFrame({\n",
    "            \"קטגוריית איכות\": [\"🔴 סיכון גבוה (Rating < 3.5)\", \"🟡 דורש מעקב (3.5 - 4.0)\", \"🟢 מלאי בריא (Rating >= 4.0)\"],\n",
    "            \"כמות מוצרים\": [len(poor), len(fair), len(good)],\n",
    "            \"אחוז מהמלאי\": [\n",
    "                f\"{(len(poor)/total_items)*100:.1f}%\",\n",
    "                f\"{(len(fair)/total_items)*100:.1f}%\",\n",
    "                f\"{(len(good)/total_items)*100:.1f}%\"\n",
    "            ],\n",
    "            \"השפעה על המדד\": [\"לא נספר במדד\", \"לא נספר במדד\", \"מהווה את אחוז המדד\"]\n",
    "        })\n",
    "        st.table(explanation_df)\n",
    "        st.info(f\"חישוב המדד: {len(good)} מוצרים בריאים מתוך {total_items} סך הכל = **{health_score:.1f}%**\")\n",
    "\n",
    "        st.markdown(\"---\")\n",
    "        \n",
    "        # גרף מגמות\n",
    "        st.subheader(f\"📈 מגמות חודשיות: {selected_cat}\")\n",
    "        filtered_df['month_year'] = filtered_df['order_date'].dt.to_period('M').astype(str)\n",
    "        monthly = filtered_df.groupby('month_year').agg({'rating_count': 'sum', 'rating': 'mean'}).reset_index()\n",
    "        \n",
    "        fig_trend = make_subplots(specs=[[{\"secondary_y\": True}]])\n",
    "        fig_trend.add_trace(go.Bar(x=monthly['month_year'], y=monthly['rating_count'], name=\"דירוגים (מכירות)\"), secondary_y=False)\n",
    "        fig_trend.add_trace(go.Scatter(x=monthly['month_year'], y=monthly['rating'], name=\"דירוג ממוצע\", line=dict(color='orange', width=3)), secondary_y=True)\n",
    "        fig_trend.update_layout(height=450, legend=dict(orientation=\"h\", y=1.1, x=0.5, xanchor=\"center\"))\n",
    "        st.plotly_chart(fig_trend, use_container_width=True)\n",
    "\n",
    "except Exception as e:\n",
    "    st.error(f\"שגיאה: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0129946f-5590-4d2a-af92-da0489fd546d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "anaconda-2025.12-py312",
   "language": "python",
   "name": "conda-env-anaconda-2025.12-py312-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
